sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
